#!/bin/bash

help() {
    echo "Usage: make-new-user [options] <user_name_1> <user_name_2>"
    echo "Each user will be created, added to the sudo group and have oh-my-zsh installed for them, with zsh set as the default shell"
    echo "Users will not have a password set by this command"
    echo "Options:"
    echo "  -h, --help      Show this help message"
    echo "  --sudoer        Add users to the sudo group"
}

_warn() {
    echo -e "\033[0;33m${1}\033[0m"
}

# parse arguments to provide -h or --help for help
while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            help
            exit 0
            ;;
        --sudoer)
            SUDOERS=1
            ;;
        -*|--*)
            echo "Invalid option: ${1}" 1>&2
            exit 1
            ;;
        *)
            USER_NAMES="${USER_NAMES} ${1}"
            ;;
    esac
    shift
done

if [[ -z ${USER_NAMES} ]]; then
    help
    exit 1
fi

if ! which zsh > /dev/null; then
    echo "Installing zsh"
    sudo apt update && sudo apt install -y zsh
fi

DEFAULT_SHELL=$(which zsh)

curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh > /tmp/ohmyzsh-install.sh
chmod +x /tmp/ohmyzsh-install.sh

create_and_configure_user() {
    local USERNAME=$1
    sudo useradd -ms $DEFAULT_SHELL ${USERNAME} \
    && if [[ ! -z $SUDOERS ]]; then sudo usermod -aG sudo ${USERNAME}; fi \
    && echo "User ${USERNAME} created" \
    && (
        sudo su ${USERNAME} -c "mkdir -p /home/${USERNAME}/.local/bin > /dev/null 2>&1"
        sudo su ${USERNAME} -c "curl -fsSL https://raw.githubusercontent.com/BaxHugh/noapm/main/noapm > ~/.local/bin/noapm; chmod +x ~/.local/bin/noapm" || _warn "Failed to install noapm"
        # Need to cd into home directory otherwise oh-my-zsh will install will error when running 'cd -'
        sudo su ${USERNAME} -c "cd /home/${USERNAME} && curl -fsSL https://raw.githubusercontent.com/BaxHugh/BaxHughConfig/main/shell-config-install.sh | bash -s -- --install-zsh --no-backup" || _warn "Failed to install shell config"
        sudo su ${USERNAME} -c "mkdir /home/${USERNAME}/.ssh/"
    ) \
    && echo "User ${USERNAME} zsh configured"
}

for user in ${USER_NAMES}; do
    create_and_configure_user ${user}
done